spring.application.name=landmarks
## Server
server.port=8080
## The port your API listens on. http://localhost:8080
## Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/landmarks_db
## jdbc:postgresql = protocol  localhost = host  5432 = port  landmarks_db = database name
spring.datasource.username=landmarks_user
spring.datasource.password=landmarks_pass
## Must match the values you passed to docker run with -e flags
spring.datasource.driver-class-name=org.postgresql.Driver
## Tells Spring which JDBC driver class to load
## JPA / Hibernate ##
spring.jpa.hibernate.ddl-auto=update
## update = Hibernate auto-creates/alters tables to match your @Entity classes
## Options: none | validate | update | create | create-drop
## Use "update" for development. Use "validate" or "none" for production.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
## Tells Hibernate to generate SQL syntax compatible with PostgreSQL
spring.jpa.show-sql=true
## Prints every SQL statement Hibernate executes to the console ? very useful for debugging
spring.jpa.properties.hibernate.format_sql=true
## Pretty-prints the SQL so it is readable
## Jackson (JSON serialisation) ##
spring.jackson.serialization.indent-output=true
## Makes JSON responses pretty-printed with indentation
